services:
  - type: web
    name: php-login-app
    env: docker
    plan: free
    repo: https://github.com/YOUR_USERNAME/php-login-backend
    branch: master
    buildCommand: ""
    startCommand: ""
    dockerfilePath: Dockerfile
